#!/usr/bin/with-contenv bash

#apt-get update

#if [ ! -f /usr/bin/pip3 ]; then
#  echo "Installing Python-Pip and Flask-SimpleLDAP"
#  apt-get install -y python3-pip
#  pip3 install --no-cache-dir -U flask-simpleldap
#elif [ -f /usr/bin/pip3 ]; then
#  echo "Pip3 installed, installing Flask-SimpleLDAP"
#  pip3 install --no-cache-dir -U flask-simpleldap
#fi

#if [ ! -d /usr/lib/python2.7/dist-packages/ldap ]; then
#  echo "Installing python-ldap"
#  apt-get install -y python-ldap
#fi

cd /app/calibre-web

pip3 install --system --target vendor -r requirements.txt
pip3 install --system --target vendor -r optional-requirements.txt
